/**  
 * This program prints out a 3N+1 sequence starting from a positive 
 * integer specified by the user.  It also counts the number of 
 * terms in the sequence, and prints out that number.
 */
public class ThreeN1 {

    public static void main(String[] args) {                

        int n;       // for computing terms in the sequence
        int counter = 0; // for counting the terms
        int c = 0; //tracks highest count
        int i = 0; //interval for less than n
        int j = 0; //particular number that is checked
        int maxI = 0;
        
        
        System.out.println("Starting point for sequence: ");
        n = TextIO.getlnInt();
        
   
        
        while(i <= n) {

        	counter = 0;
        	j = i;
        	while(j>1) {
        		if(j%2 == 0) {
        			j = j/2; //even
        		}
        		else {
        			j = (3*j) + 1; //odd
        		}
        		counter ++;
        	}	
        	if(counter > c) { 
        		c = counter;
        		maxI = i;    
        		//System.out.println("counter: " + counter);
        	}
        	i++;
        }
 
        System.out.println("Longest sequence possible from 1-" + n + " generated by number: " + maxI + ". Length of sequence: "+ c+ " terms.");

    }  // end of main()

}  // end of class ThreeN1
